package strategy

import (
	"context"
	"fmt"
	"time"

	"github.com/shopspring/decimal"
)

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	StrategyID  string
	Symbol      string
	Action      SignalAction
	Quantity    decimal.Decimal
	Price       decimal.Decimal
	TimeInForce string
	Confidence  decimal.Decimal // 0-1, confidence level
	Reason      string          // Human-readable reason for signal
	GeneratedAt time.Time
}

// SignalAction represents the type of trading action.
type SignalAction string

const (
	SignalActionBuy   SignalAction = "BUY"
	SignalActionSell  SignalAction = "SELL"
	SignalActionClose SignalAction = "CLOSE"
	SignalActionHold  SignalAction = "HOLD"
)

// MarketData represents current market data for a symbol.
type MarketData struct {
	Symbol    string
	LastPrice decimal.Decimal
	BidPrice  decimal.Decimal
	AskPrice  decimal.Decimal
	Volume24h decimal.Decimal
	High24h   decimal.Decimal
	Low24h    decimal.Decimal
	Timestamp time.Time
}

// StrategyContext provides data and utilities to strategies.
type StrategyContext struct {
	MarketData   MarketData
	CurrentPrice decimal.Decimal
	Position     PositionInfo
	Balance      BalanceInfo
	Timestamp    time.Time
}

// PositionInfo represents current position information.
type PositionInfo struct {
	Symbol        string
	Side          string
	Quantity      decimal.Decimal
	EntryPrice    decimal.Decimal
	CurrentPrice  decimal.Decimal
	UnrealizedPnL decimal.Decimal
	RealizedPnL   decimal.Decimal
}

// BalanceInfo represents account balance information.
type BalanceInfo struct {
	Total     decimal.Decimal
	Available decimal.Decimal
	Locked    decimal.Decimal
}

// Strategy defines the interface for trading strategies.
type Strategy interface {
	// Name returns the strategy name.
	Name() string

	// Version returns the strategy version.
	Version() string

	// OnTick is called on each market tick with current market data.
	// Returns a signal if a trading action should be taken, or nil if no action.
	OnTick(ctx context.Context, data *StrategyContext) (*Signal, error)

	// OnOrderFilled is called when an order is filled.
	OnOrderFilled(ctx context.Context, orderID string, filledQty, filledPrice decimal.Decimal) error

	// OnOrderCanceled is called when an order is canceled.
	OnOrderCanceled(ctx context.Context, orderID string) error

	// GetParameters returns the strategy parameters for configuration.
	GetParameters() map[string]interface{}

	// SetParameters updates strategy parameters.
	SetParameters(params map[string]interface{}) error

	// Reset resets the strategy state.
	Reset() error
}

// StrategyMetadata contains metadata about a strategy.
type StrategyMetadata struct {
	ID          string
	Name        string
	Version     string
	Description string
	Author      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Enabled     bool
	Parameters  map[string]interface{}
}

// StrategyRegistry manages available strategies.
type StrategyRegistry struct {
	strategies map[string]Strategy
}

// NewStrategyRegistry creates a new strategy registry.
func NewStrategyRegistry() *StrategyRegistry {
	return &StrategyRegistry{
		strategies: make(map[string]Strategy),
	}
}

// Register registers a strategy.
func (sr *StrategyRegistry) Register(id string, strategy Strategy) error {
	if _, exists := sr.strategies[id]; exists {
		return fmt.Errorf("strategy %s already registered", id)
	}
	sr.strategies[id] = strategy
	return nil
}

// Get retrieves a strategy by ID.
func (sr *StrategyRegistry) Get(id string) (Strategy, error) {
	strategy, exists := sr.strategies[id]
	if !exists {
		return nil, fmt.Errorf("strategy %s not found", id)
	}
	return strategy, nil
}

// List returns all registered strategies.
func (sr *StrategyRegistry) List() map[string]Strategy {
	return sr.strategies
}

// Unregister removes a strategy.
func (sr *StrategyRegistry) Unregister(id string) error {
	if _, exists := sr.strategies[id]; !exists {
		return fmt.Errorf("strategy %s not found", id)
	}
	delete(sr.strategies, id)
	return nil
}
